backend:
  name: github
  repo: tamilcode-org/tamilcode-content

media_folder: content/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: content/post
    create: true
    fields:
      - { name: path, label: Path }
      - { name: layout, label: Layout, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image, required: false }
      - name: tag
        label: Tag
        widget: list
        fields:
          - { name: id, label: ID }
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: image, label: Image, widget: image, required: false }
      - name: author
        label: Author
        widget: object
        fields:
          - { name: id, label: ID }
          - { name: name, label: Name }
          - { name: bio, label: Bio }
          - { name: twitter, label: Twitter }
          - { name: facebook, label: Facebook }
          - { name: website, label: Website }
          - { name: location, label: Location }
          - { name: avatar, label: Avatar, widget: image, required: false }
          - { name: profile_image, label: Profile Image, widget: image, required: false }
          

